receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
  filelog:
    include: [ /tmp/loggenerator-aws.log ]

processors:
  lua:
    script: "/sumologic/pkg/processor/luaprocessor/examples/script.lua"
    function: "process"

exporters:
  logging:
    logLevel: debug

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [lua]
      exporters: [logging]

    metrics:
      receivers: [hostmetrics]
      processors: [lua]
      exporters: [logging]
